### ISSUE TITLE
Dokumentation state Tracker

### ISSUE THREAD

**Issue by TLTimeplex** [TST-Systems/Voice-of-Time#42]
# Voice of Time
- [x] ├── Cmd/
- [x] │&ensp;&ensp;&ensp;├── Commands/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Chat.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Connect.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Disconnect.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Exit.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Help.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Select.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Stash.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── User.cs
- [x] │&ensp;&ensp;&ensp;└── CommandHandler.cs
- [x] ├── Shared/
- [x] │&ensp;&ensp;&ensp;├── Functions/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── Requests.cs
- [x] │&ensp;&ensp;&ensp;└── ClientData.cs
- [x] ├── Transfer/
- [x] │&ensp;&ensp;&ensp;└── ClientSocket.cs
- [x] ├── User/
- [x] │&ensp;&ensp;&ensp;└── Client.cs
- [x] ├── Program.cs
- [x] └── Usings.cs

# Voice of Time Server/
- [x] ├── Config/
- [x] │&ensp;&ensp;&ensp;└── ServerConfig.cs
- [x] ├── RequestExecuter/
- [x] │&ensp;&ensp;&ensp;├── Interface/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── IServerRequestExecuter.cs
- [x] │&ensp;&ensp;&ensp;├── CommunicationGetKeyAndSecure.cs
- [x] │&ensp;&ensp;&ensp;├── PrivatChatInviteAccept.cs
- [x] │&ensp;&ensp;&ensp;├── PrivatChatInviteUser.cs
- [x] │&ensp;&ensp;&ensp;├── PrivatChatRegister.cs
- [x] │&ensp;&ensp;&ensp;├── PublicUserGet.cs
- [x] │&ensp;&ensp;&ensp;├── PublicUserGetIDList.cs
- [x] │&ensp;&ensp;&ensp;├── ServerGetIdentitiy.cs
- [x] │&ensp;&ensp;&ensp;├── ServerPublicKeyExchange.cs
- [x] │&ensp;&ensp;&ensp;├── StashAdd.cs
- [x] │&ensp;&ensp;&ensp;├── StashDelete.cs
- [x] │&ensp;&ensp;&ensp;├── StashGet.cs
- [x] │&ensp;&ensp;&ensp;├── StashList.cs
- [x] │&ensp;&ensp;&ensp;├── UserRegister.cs
- [x] │&ensp;&ensp;&ensp;├── UserSetUsername.cs
- [x] │&ensp;&ensp;&ensp;└── UserVerify.cs
- [x] ├── Shared/
- [x] │&ensp;&ensp;&ensp;└── ServerData.cs
- [x] ├── Transfer/
- [x] │&ensp;&ensp;&ensp;├── SocketHandler.cs
- [x] │&ensp;&ensp;&ensp;└── SocketServer.cs
- [x] ├── User/
- [x] │&ensp;&ensp;&ensp;└── Server.cs
- [x] └── Program.cs

# VoTCore
- [x] ├── Algorithms/
- [x] │&ensp;&ensp;&ensp;├── Base36.cs
- [x] │&ensp;&ensp;&ensp;└── LoadingBar.cs
- [x] ├── Communication/
- [x] │&ensp;&ensp;&ensp;├── Data/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── FileMessage.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── Message.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── MessageStatus.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── TextMessage.cs
- [x] │&ensp;&ensp;&ensp;├── Extra/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── ChatUserState.cs
- [x] │&ensp;&ensp;&ensp;├── PrivatChat.cs
- [x] │&ensp;&ensp;&ensp;└── TextChat.cs
- [x] ├── Controll/
- [x] │&ensp;&ensp;&ensp;├── IConsoleCommand.cs
- [x] │&ensp;&ensp;&ensp;├── IConsoleCommandAsync.cs
- [x] │&ensp;&ensp;&ensp;└── IConsoleCommandSync.cs
- [x] ├── Data/
- [x] │&ensp;&ensp;&ensp;├── InternalException.cs
- [x] │&ensp;&ensp;&ensp;└── StashMessage.cs
- [x] ├── Exceptions/
- [x] │&ensp;&ensp;&ensp;├── EntryAlreadyExistsExeption.cs
- [x] │&ensp;&ensp;&ensp;├── PackageBodyNullException.cs
- [x] │&ensp;&ensp;&ensp;├── PublicKeyMissingExeption.cs
- [x] │&ensp;&ensp;&ensp;└── UnauthorizedCharExeption.cs
- [x] ├── Package/
- [x] │&ensp;&ensp;&ensp;├── AbsData/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── AbsData_Invite.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── AbsData_InviteAccept.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── AbsData_Receipt.cs
- [x] │&ensp;&ensp;&ensp;├── AData/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── AData.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── AData_Long.cs
- [x] │&ensp;&ensp;&ensp;├── Header/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── HeaderAck.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── HeaderReq.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── HeaderStd.cs
- [x] │&ensp;&ensp;&ensp;├── Interfaces/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── IVOTPBody.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── IVOTPHeader.cs
- [x] │&ensp;&ensp;&ensp;├── SData/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── SData.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── SData_Guid.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── SData_Int.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── SData_InternalException.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── SData_Long.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── SData_String.cs
- [x] │&ensp;&ensp;&ensp;├── SecData/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── SecData_Key_Aes.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── SecData_Key_RSA.cs
- [x] │&ensp;&ensp;&ensp;├── StashData/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;├── StashData.cs
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── StashData_Add.cs
- [x] │&ensp;&ensp;&ensp;├── VOTP.cs
- [x] │&ensp;&ensp;&ensp;└── VOTPInfo.cs
- [x] ├── Secure/
- [x] │&ensp;&ensp;&ensp;├── Interfaces/
- [x] │&ensp;&ensp;&ensp;│&ensp;&ensp;&ensp;└── IRSACrypt.cs
- [x] │&ensp;&ensp;&ensp;├── CryproManager.cs
- [x] │&ensp;&ensp;&ensp;├── PublicKeyStorage.cs
- [x] │&ensp;&ensp;&ensp;└── PublicRSA.cs
- [x] ├── User/
- [x] │&ensp;&ensp;&ensp;└── PublicClient.cs
- [x] └── Constans.cs

# VoTTest/
- [x] ├── Core/
- [x] │&ensp;&ensp;&ensp;├── ADataTest.cs
- [x] │&ensp;&ensp;&ensp;├── Base36Test.cs
- [x] │&ensp;&ensp;&ensp;├── ClientTest.cs
- [x] │&ensp;&ensp;&ensp;├── SecDataTest.cs
- [x] │&ensp;&ensp;&ensp;├── StashDataTest.cs
- [x] │&ensp;&ensp;&ensp;└── VOTPTest.cs
- [x] └── Usings.cs
